import React from 'react';
import { Pressable, StyleProp, StyleSheet, Text, TextStyle, View, ViewStyle } from 'react-native';
import { useApp } from '../context/AppContext';
import { colors, darkColors } from '../utils/theme';
export function Screen({ children }: { children: React.ReactNode }): React.JSX.Element { const { settings } = useApp(); const c = settings.theme === 'dark' ? darkColors : colors; return <View style={[styles.screen, { backgroundColor: c.background }]}>{children}</View>; }
export function Card({ children, style, label }: { children: React.ReactNode; style?: StyleProp<ViewStyle>; label?: string }): React.JSX.Element { const { settings } = useApp(); const c = settings.theme === 'dark' ? darkColors : colors; return <View accessible accessibilityLabel={label} style={[styles.card, { backgroundColor: c.surface, borderColor: c.border }, style]}>{children}</View>; }
export function AppText({ children, style, heading = false }: { children: React.ReactNode; style?: StyleProp<TextStyle>; heading?: boolean }): React.JSX.Element { const { settings } = useApp(); const c = settings.theme === 'dark' ? darkColors : colors; return <Text accessibilityRole={heading ? 'header' : undefined} style={[{ color: c.text, fontSize: 16 * settings.textScale, lineHeight: 24 * settings.textScale }, heading && styles.heading, style]}>{children}</Text>; }
export function Button({ label, onPress, secondary = false, danger = false, disabled = false }: { label: string; onPress?: () => void; secondary?: boolean; danger?: boolean; disabled?: boolean }): React.JSX.Element { const { settings } = useApp(); const c = settings.theme === 'dark' ? darkColors : colors; const backgroundColor = danger ? colors.emergency : secondary ? c.surface : c.primary; return <Pressable accessible accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={[styles.button, { minHeight: settings.largeTouchTargets ? 52 : 44, backgroundColor, borderColor: secondary ? c.primary : backgroundColor, opacity: disabled ? .5 : 1 }]}><Text style={{ color: secondary ? c.primary : '#fff', fontWeight: '700', fontSize: 16 * settings.textScale }}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, card: { borderWidth: 1, borderRadius: 14, padding: 16 }, heading: { fontSize: 28, fontWeight: '800', lineHeight: 36 }, button: { alignItems: 'center', justifyContent: 'center', borderRadius: 12, borderWidth: 1, paddingHorizontal: 16, marginVertical: 6 } });
