import React, { useState } from 'react';
import { Alert, Modal, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { BottomTabScreenProps } from '@react-navigation/bottom-tabs';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { AppText, Button, Card, Screen } from '../components/UI';
import { appointments } from '../utils/data'; import { RootParams, TabParams } from '../navigation/RootNavigator'; import { useApp } from '../context/AppContext'; import { formatTime } from '../utils/theme';
export function CareScreen({ navigation }: BottomTabScreenProps<TabParams, 'Care'>): React.JSX.Element {
 const [showAdd, setShowAdd] = useState(false); return <Screen><ScrollView contentContainerStyle={s.content}><AppText heading>Your appointments</AppText><AppText>Upcoming visits and questions to ask</AppText>{appointments.map(a => <Card key={a.id}><AppText style={s.title}>{a.title}</AppText><AppText>{a.dateAndTime}{'\n'}{a.location}</AppText><Button label="View appointment" secondary onPress={() => navigation.getParent()?.navigate('AppointmentDetail', { appointment: a })} /></Card>)}<Button label="Add appointment" onPress={() => setShowAdd(true)} /><Button label="Health log" secondary onPress={() => navigation.getParent()?.navigate('HealthLog')} /><Button label="Emergency assistance" danger onPress={() => navigation.getParent()?.navigate('Emergency')} /><SimpleModal visible={showAdd} title="Add appointment" onClose={() => setShowAdd(false)}><Input label="Appointment name" /><Input label="Date and time" /><Button label="Save appointment" disabled /></SimpleModal></ScrollView></Screen>;
}
export function AppointmentDetailScreen({ route, navigation }: NativeStackScreenProps<RootParams, 'AppointmentDetail'>): React.JSX.Element { const { appointment } = route.params; return <Screen><ScrollView contentContainerStyle={s.content}><AppText heading>{appointment.title}</AppText><AppText secondary>{appointment.dateAndTime} • {appointment.location}</AppText><Card><AppText style={s.title}>Before you go</AppText><AppText>Bring insurance card • Arrive 10 minutes early</AppText></Card><Card tone="info"><AppText style={[s.title, s.darkText]}>Questions for the therapist</AppText><AppText style={s.darkText}>{'• Is my knee pain improving?\n• Which home exercises are safest?'}</AppText></Card><Button label="Check in" onPress={() => navigation.navigate('HealthLog')} /><Button label="Message caregiver" secondary onPress={() => navigation.navigate('Tabs', { screen: 'Messages' } as never)} /></ScrollView></Screen>; }
export function HealthLogScreen(): React.JSX.Element { const { logs, addLog } = useApp(); const [symptom, setSymptom] = useState(''); const [notes, setNotes] = useState(''); const save = () => { if (!symptom.trim()) { Alert.alert('Choose a symptom to continue.'); return; } addLog(symptom, notes.trim()); setSymptom(''); setNotes(''); Alert.alert('Health log saved.'); }; return <Screen><ScrollView contentContainerStyle={s.content}><AppText heading>How are you feeling?</AppText><AppText>Record symptoms without animation or pressure</AppText><Input label="Symptom" value={symptom} onChangeText={setSymptom} placeholder="Knee pain, fatigue, headache…" /><Input label="Private notes (optional)" value={notes} onChangeText={setNotes} multiline placeholder="Add details about how you feel" /><Button label="Save today’s log" onPress={save} /><AppText style={s.section}>Recent health logs</AppText>{logs.length === 0 ? <AppText>No symptoms logged yet.</AppText> : logs.map(log => <Card key={log.id}><AppText style={s.title}>{log.symptom}</AppText><AppText>{log.notes || 'No note added'}{'\n'}{formatTime(log.recordedAt)}</AppText></Card>)}</ScrollView></Screen>; }
export function EmergencyScreen(): React.JSX.Element { return <Screen><ScrollView contentContainerStyle={s.content}><AppText heading>Emergency assistance</AppText><AppText secondary>Use only when you or someone else may be in danger.</AppText><Card tone="info"><AppText style={[s.title, s.darkText]}>Your location</AppText><AppText style={s.darkText}>Ready to share only after confirmation.</AppText></Card><Button label="Call emergency services" danger onPress={() => Alert.alert('Emergency services called', 'Emergency services have been called.')} /><Button label="Alert caregiver" secondary disabled /><Card><AppText style={s.title}>What happens next</AppText><AppText>{'1. You confirm the action\n2. A static status stays visible\n3. Response acknowledgment is recorded'}</AppText></Card></ScrollView></Screen>; }
function Input({ label, value = '', onChangeText, placeholder, multiline = false }: { label: string; value?: string; onChangeText?: (v: string) => void; placeholder?: string; multiline?: boolean }): React.JSX.Element { return <View style={s.inputWrap}><AppText style={s.label}>{label}</AppText><TextInput accessible accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder || label} multiline={multiline} style={[s.input, multiline && { minHeight: 90, textAlignVertical: 'top' }]} /></View>; }
function SimpleModal({ visible, title, onClose, children }: { visible: boolean; title: string; onClose: () => void; children: React.ReactNode }): React.JSX.Element { return <Modal visible={visible} transparent animationType="none" onRequestClose={onClose}><View style={s.overlay}><Card><AppText heading>{title}</AppText>{children}<Button label="Cancel" secondary onPress={onClose} /></Card></View></Modal>; }
const s = StyleSheet.create({ content: { padding: 20, paddingBottom: 32, gap: 12, maxWidth: 760, width: '100%', alignSelf: 'center' }, title: { fontWeight: '700', fontSize: 18 }, section: { fontWeight: '800', fontSize: 20, marginTop: 8 }, inputWrap: { gap: 5 }, label: { fontWeight: '700' }, input: { borderWidth: 1, borderColor: '#7D91A8', backgroundColor: '#fff', color: '#10233F', borderRadius: 10, minHeight: 50, padding: 12, fontSize: 16 }, overlay: { flex: 1, backgroundColor: '#0008', justifyContent: 'center', padding: 24 }, darkText: { color: '#10233F' } });
